name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install code and install dependencies
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/WithBuddy_be_2.0
            git pull origin main
            sudo npm install -g npm  # 최신 npm 버전으로 업데이트
            npm install
            npm install openapi-types@^7  # openapi-types 설치
            npm audit fix  # 취약점 자동 수정
            npx prisma generate
            npx prisma migrate deploy

      - name: Execute code and restart app
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/WithBuddy_be_2.0
            pm2 kill || true  # pm2 프로세스가 없을 경우 에러 무시
            npm run build
            pm2 start ecosystem.config.json
